language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls==4.0 codeclimate-test-reporter

# Test
script:
  - coverage run --source=vario setup.py test
after_success:
  codeclimate-test-reporter

# Notifcation preferences for travis apparently go in here?!
notifications:
  email:
    on_success: never
    on_failure: change

